export default {
    SELECT_PROJECT: 0,
    SELECT_IMAGE: 1,
    BASIC_SETTINGS: 2,
    ADD_BOOTSCRIPTS: 3,
    ADD_RESERVED_IP: 4,
    ADD_SSH_KEYS: 5,
    CHANGE_IMAGE_VERSION: 6,
    CONFIRMATION: 7
};
